name: Daily AI News

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run agent
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: poetry run run-agent